// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvXII1XF6_FWWYYfhpypNQS5sw1txExwY',
    appId: '1:171227597422:web:e20213b7f3cfea2ba5747f',
    messagingSenderId: '171227597422',
    projectId: 'ai-ktu-notes-app',
    authDomain: 'ai-ktu-notes-app.firebaseapp.com',
    storageBucket: 'ai-ktu-notes-app.firebasestorage.app',
    measurementId: 'G-PNJ98N6WCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvYF6pEvsXkCaJFLOqWoAU1W-F6-X_wfQ',
    appId: '1:171227597422:android:94b2120978d2bb7ba5747f',
    messagingSenderId: '171227597422',
    projectId: 'ai-ktu-notes-app',
    storageBucket: 'ai-ktu-notes-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5-XwVS_mNipVdk-WX7ohk9ZPAQ2RzDG0',
    appId: '1:171227597422:ios:18ce0754a9b4f790a5747f',
    messagingSenderId: '171227597422',
    projectId: 'ai-ktu-notes-app',
    storageBucket: 'ai-ktu-notes-app.firebasestorage.app',
    iosBundleId: 'com.example.aiKtuNotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5-XwVS_mNipVdk-WX7ohk9ZPAQ2RzDG0',
    appId: '1:171227597422:ios:18ce0754a9b4f790a5747f',
    messagingSenderId: '171227597422',
    projectId: 'ai-ktu-notes-app',
    storageBucket: 'ai-ktu-notes-app.firebasestorage.app',
    iosBundleId: 'com.example.aiKtuNotesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvXII1XF6_FWWYYfhpypNQS5sw1txExwY',
    appId: '1:171227597422:web:ea84428a9b11744aa5747f',
    messagingSenderId: '171227597422',
    projectId: 'ai-ktu-notes-app',
    authDomain: 'ai-ktu-notes-app.firebaseapp.com',
    storageBucket: 'ai-ktu-notes-app.firebasestorage.app',
    measurementId: 'G-TMVPWLQFFK',
  );
}
